org: tormozz48
app: football-chat-bot-aws
service: football-chat-bot-aws
frameworkVersion: '3'

custom:
  tableName: 'events-table-${sls:stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      docker: true
      sharedDb: true
      inMemory: false
      migrate: true
      seed: false
      noStart: false
      convertEmptyValues: true
      dockerImage: amazon/dynamodb-local

plugins:
  - serverless-jest-plugin
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    EVENTS_TABLE: ${self:custom.tableName}
    TELEGRAM_BOT_TOKEN: ${param:telegramBotToken}
    TELEGRAM_BOT_WEBHOOK_URL: ${param:telegramBotWebhookUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ EventsTable, Arn ]

functions:
  ping:
    handler: src/lambda/ping.handler
    events:
      - httpApi:
          path: /ping
          method: get
  telegram:
    handler: src/lambda/telegram.handler
    events:
      - httpApi:
          path: /telegram
          method: post
  eventAdd:
    handler: src/lambda/actions/event-add.eventAdd
    events:
      - httpApi:
          path: /eventAdd
          method: post
  eventInfo:
    handler: src/lambda/actions/event-info.eventInfo
  eventRemove:
    handler: src/lambda/actions/event-remove.eventRemove
  memberAdd:
    handler: src/lambda/actions/member-add.memberAdd
  memberRemove:
    handler: src/lambda/actions/member-remove.memberRemove

resources:
  Resources:
    EventsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: chatId
            AttributeType: N
          -
            AttributeName: eventDate
            AttributeType: N
        KeySchema:
          -
            AttributeName: chatId
            KeyType: HASH
          -
            AttributeName: eventDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1