name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Configure AWS credentials
        run: npm run serverless config credentials --provider aws --overwrite --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Deploy
        run: npm run deploy
